version: '3.7'

services:
  mongo:
    image: 'mongo:latest'
    container_name: 'mongo'
    ports:
      - 27017:27017
  bot:
    build: './'
    container_name: 'bot'
    volumes:
      - './src:/app/src'
    env_file: './.env'
    depends_on: 
      - mongo
    